site_name: Initiative for Ethical Academic Ties at KIT
# repo_url: https://github.com/ieat-kit/ieat-kit.github.io
# edit_uri: edit/main/docs/
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  language: en
  logo: images/Logo IEAT 192.png
  favicon: images/favicon.ico
  features:
  - navigation.tabs
  - content.action.edit
  - content.action.view
#  palette:
#    primary:
#    accent:
# I'll keep it here for the future
# plugins:
#  - blog
extra:
 social:
    # - icon: fontawesome/brands/mastodon
    #   link: 
    #   name: 
    # - icon: fontawesome/brands/twitter
    #   link: 
    #   name: 
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ieat.kit
      name: IEAT's instagram account 
    # - icon: fontawesome/brands/facebook
    #   link: 
    #   name: 
    # - icon: fontawesome/brands/github
    #   link: 
    #   name: 
    - icon: fontawesome/regular/envelope
      link: mailto:info.ieat.kit@protonmail.com
      name: email of IEAT
    
nav:
- About us / Über uns:
  - index.md
  - index-de.md
- To KIT employees / Für Beschäftigte des KIT:
  - to-kit-employees.md
  - to-kit-employees-de.md
- Our Letter / Unser Brief: 
  - letter.md
  - letter-de.md
- Timeline:
  - timeline.md
- News: 
  - news.md
  - news-de.md
- Imprint / Impressum: imprint.md